/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.oods.cboletim.ui;
import br.com.oods.cboletim.dao.*;
import static br.com.oods.cboletim.dao.AlunoDAOJDBC.GET_ALL_ALUNOS;
import static br.com.oods.cboletim.dao.PessoaDAOJDBC.GET_ALL_PESSOAS;
import static br.com.oods.cboletim.dao.AlunoDAOJDBC.log;
import br.com.oods.cboletim.exception.PersistenceException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.log4j.Logger;


/**
 *
 * @author Vinicius
 */
public class PrincipalFrame extends javax.swing.JFrame {
   
    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmenrelalunos = new javax.swing.JMenuItem();
        jmrelusuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastrar");

        jMenuItem1.setText("Usuários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Alunos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");

        jmenrelalunos.setText("Alunos");
        jmenrelalunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenrelalunosActionPerformed(evt);
            }
        });
        jMenu2.add(jmenrelalunos);

        jmrelusuarios.setText("Usuários");
        jmrelusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmrelusuariosActionPerformed(evt);
            }
        });
        jMenu2.add(jmrelusuarios);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ListaPessoasFrame frame = new ListaPessoasFrame(); 
        frame.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       ListaAlunosFrame frame = new ListaAlunosFrame(); 
       frame.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmenrelalunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenrelalunosActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        try{
            AlunoDAO dao = new AlunoDAOJDBC();
            conn = ConnectionManager.getConnection();
            stmt = AlunoDAOJDBC.createStatementWithLog(conn, GET_ALL_ALUNOS);
            rs = stmt.executeQuery();
        }catch(SQLException e) {
                    String errorMsg = "Erro ao consultar Aluno por nome!";
                    log.error(errorMsg, e);
                    throw new PersistenceException(errorMsg, e);
        }                
        
        try{
            
            JRResultSetDataSource relatResul = new JRResultSetDataSource(rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("ireport/RelatorioBrancoAlunos.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint);
            jv.setVisible(true);
        }catch (JRException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao chamar relatório! \nErro: "+ ex);
        }finally {
                    ConnectionManager.closeAll(conn, stmt, rs);
            }
        
        
    }//GEN-LAST:event_jmenrelalunosActionPerformed

    private void jmrelusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmrelusuariosActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        try{
            PessoaDAO dao = new PessoaDAOJDBC();
            conn = ConnectionManager.getConnection();
            stmt = PessoaDAOJDBC.createStatementWithLog(conn, GET_ALL_PESSOAS);
            rs = stmt.executeQuery();
        }catch(SQLException e) {
                    String errorMsg = "Erro ao consultar Usuario por nome!";
                    log.error(errorMsg, e);
                    throw new PersistenceException(errorMsg, e);
        }                
        
        try{
            
            JRResultSetDataSource relatResul = new JRResultSetDataSource(rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("ireport/RelatorioBrancoUsuarios.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint);
            jv.setVisible(true);
        }catch (JRException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao chamar relatório! \nErro: "+ ex);
        }finally {
                    ConnectionManager.closeAll(conn, stmt, rs);
            }
        
        
    }//GEN-LAST:event_jmrelusuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmenrelalunos;
    private javax.swing.JMenuItem jmrelusuarios;
    // End of variables declaration//GEN-END:variables
}
